# Written by Adam Reimer
---
- name: Validate configuration of the switch
  hosts: switches
  gather_facts: no
  connection: network_cli


  tasks:
  
     # Template code for collecting data from the device via show commands
   #- name: Run a show command on the device and collect the result
   #  ios command:
   #    commands:
   #      - show command
   #  register: show_command_config
      
      
    - name: Run a show interfaces switchport on the device and save the result to show_int_config.
      ios_command:
        commands:
          - show interfaces switchport

      register: show_int_config 


    - name: Run a show crypto key mypubkey rsa on the device and save the result to show_key_config.
      ios_command:
        commands:
          - show crypto key mypubkey rsa

      register: show_key_config


    - name: Run a show interfaces vlan 1 on the device and save the result to show_vlan_config
      ios_command:
        commands:
          - show interfaces vlan 1

      register: show_vlan_config
    
    
     # Template code for Validating the device using the data collected from the previously executed show commands
   #- name: check the previously collected show command to test device configuration
   #  assert:
   #    that:
   #      - "'desired string value' in (show_command_config.stdout_lines[0])"
   #    success_msg: "message to output if the following is true."
   #    fail_msg: "message to output if the following is false."
    

    - name: Check if trunking has been sucessfully enabled on the device.
      assert:
        that:
          - "'Administrative Mode: trunk' in (show_int_config.stdout_lines[0])"
          - "'Operational Mode: trunk' in (show_int_config.stdout_lines[0])"
        success_msg: "Trunk configuration found."
        fail_msg: "Trunk configuration not found."


    - name: Check if the crypto key has been sucessfully created on the device.
      assert:
        that:
          - "'Key type: RSA KEYS' in (show_key_config.stdout_lines[0])"
        success_msg: "Crypto key found"
        fail_msg: "Crypto key not found."
        

    - name: Check if Vlan1 is up on the device.
      assert:
        that:
          - "'Vlan1 is up, line protocol is up' in (show_vlan_config.stdout_lines[0])"
        success_msg: "Vlan 1 is up."
        fail_msg: "Vlan 1 is down."

...
